name: Smoke test for the Kubernetes cluster
description: |
  Spins up a kind cluster and asserts that the cluster forms, pods start up without issue,
  quorum forms and leader is elected, killing (and the k8s restart of) a leader eventually
  elects a new leader, rolling updates are working as expected.

inputs:
  app_name:
    description: name of the cluster, namespace etc (wherever we would use "kave", which it also defaults to)
    default: "kave"
  image_registry:
    description: name of the container registry
    default: "ghcr.io"
    required: true
  image_repo:
    description: name of the image repository
    default: "balits/kave"
    required: true
  image_tag:
    description: tag of the image
    default: "latest"
    required: true
  github_token:
    description: secret github token
    required: true

runs:
  using: composite
  steps:
    - name: Verify kubectl is installed
      shell: bash
      run: kubectl version --client
    
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    
    - name: Install Helm
      uses: azure/setup-helm@v5.0.0

    - name: Install yq
      shell: bash
      run: |
        wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x /usr/local/bin/yq

    - name: Patch Chart.yaml appVersion
      shell: bash
      env:
        APP_VERSION: ${{ inputs.image_tag }}
      run: |
        yq eval '.appVersion = strenv(APP_VERSION)' -i ./charts/kave/Chart.yaml

    # this should set KUBECONFIG inside the smoke job,
    - name: Create kind cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: ${{ inputs.app_name }}

    - name: Pull and load image into kind
      shell: bash
      env:
        IMAGE: ${{ inputs.image_registry }}/${{ inputs.image_repo }}:${{ inputs.image_tag }}
      run: |
        echo "${{ inputs.github_token }}" | \
           docker login ${{ inputs.image_registry }} -u ${{ github.actor }} --password-stdin
        docker pull $IMAGE
        kind load docker-image $IMAGE --name ${{ inputs.app_name }}

    - name: Install Helm Chart
      shell: bash
      run: |
        helm upgrade --install ${{ inputs.app_name }} ./charts/kave \
          --namespace ${{ inputs.app_name }} \
          --create-namespace \
          --set image.pullPolicy=Never \
          --set image.registry=${{ inputs.image_registry }} \
          --set image.repository=${{ inputs.image_repo }} \
          --set image.tag=${{ inputs.image_tag }} \
          --set config.ratelimiter.read.rps=5000 \
          --set config.ratelimiter.read.burst=5000 \
          --set config.ratelimiter.write.rps=5000 \
          --set config.ratelimiter.write.burst=5000 \
          --set voters.replicas=3 \
          --wait \
          --timeout=3m

    - name: Run smoke tests
      env:
        # this should be the path to which kind-action export its conf
        KUBECONFIG: /home/runner/.kube/config
        NAMESPACE: ${{ inputs.app_name }} 
        CLUSTER_SIZE: 3
        URL: "http://127.0.0.1:8080" # force IPv4
      shell: bash
      run: |
        # forwards the port in a loop to survice node kills
        (while true; do
          kubectl port-forward svc/${{ inputs.app_name }}-external 8080:80 \
            --address 127.0.0.1 \
            --namespace ${{ inputs.app_name }} > /dev/null 2>&1
          sleep 1
        done) &
        LOOP_PID=$!
        sleep 5

        go test ./test/smoke/... -v -count=1 --timeout 5m --tags=smoke
        TEST_RESULT=$?

        kill -9 $LOOP_PID 2>/dev/null || true
        exit $TEST_RESULT
      
    - name: Dump pod logs on failure
      if: failure()
      shell: bash
      run: |
        kubectl get pods -n ${{ inputs.app_name }}
        
        for pod in $(kubectl get pods -n ${{ inputs.app_name }} \
            -o jsonpath='{.items[*].metadata.name}'); do
          echo "===== logs for pod $pod ====="
          kubectl logs "$pod" -n ${{ inputs.app_name }} --tail=100 || true
        done


    # - name: Wait for cluster readiness
    #   shell: bash
    #   env:
    #     STATEFULSET_NAME: statefulset/kave-voter
    #   run: |
    #     kubectl rollout status $STATEFULSET_NAME \
    #       --namespace  ${{ inputs.app_name }} \
    #       --timeout 2m

    # - name: Port-forward kave service in the background
    #   shell: bash
    #   run: |
    #     kubectl port-forward svc/kave 8080:80 \
    #       --namespace kave &
    #     sleep 5

    # - name: Run Smoke Tests
    #   shell: bash
    #   env:
    #     # KUBECONFIG gets handled by helm/kind-actions
    #     NAMESPACE: kave
    #     CLUSTER_SIZE: 3
    #     URL: "http://localhost:8080" 
    #   run: |
    #     make smoke-test \
    #       SMOKE_REGISTRY=${{ inputs.image_registry }} \
    #       SMOKE_REPO=${{ inputs.image_repo }} \
    #       SMOKE_TAG=${{ inputs.image_tag }}