apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kave.name" . }}-config
  labels:
    {{- include "kave.labels" . | nindent 4 }}
data:
  clusterConfig.json: |
    {
      "logger": {
        "kind": {{  .Values.config.logger.kind | quote }},
        "level": {{  .Values.config.logger.level | quote }}
      },
      "checkpoint_interval_minutes": {{  .Values.config.checkpointIntervalMinutes }},
      "peer_discovery": {
        "mode": {{ .Values.config.peerDiscovery.mode | quote }},
        "expected_count": {{ .Values.voters.replicas }}
      },
      "kv": {
        "max_key_size": {{ .Values.config.kv.maxKeySize }},
        "max_value_size": {{ .Values.config.kv.maxValueSize }}
      },
      "storage": {
          "kind": {{  .Values.config.storage.kind | quote }},
          "data_dir": {{  .Values.config.storage.dataDir | quote }}
      },
      "compaction": {
        "threshold": {{  .Values.config.compaction.threshold }},
        "interval_minutes": {{  .Values.config.compaction.intervalMinutes }},
        "max_rev_gap": {{  .Values.config.compaction.maxRevGap }}
      },
      "ot": {
        "slot_count": {{ .Values.config.ot.slotCount }},
        "slot_size": {{  .Values.config.ot.slotSize }},
        "token_ttl_sec": {{  .Values.config.ot.tokenTTLSec }}
      },
      "ratelimiter": {
          "read": {
              "rps":  {{ .Values.config.ratelimiter.read.rps }},
              "burst": {{ .Values.config.ratelimiter.read.burst }}
          },
          "write": {
              "rps": {{ .Values.config.ratelimiter.write.rps }},
              "burst": {{ .Values.config.ratelimiter.write.burst }}
          }
      },
      "mtls": {
        "cert_file": {{ .Values.config.mtls.certFile | quote }},
        "key_file": {{ .Values.config.mtls.keyFile | quote }},
        "ca_file": {{ .Values.config.mtls.caFile | quote }}
      },
      "raft": {
        "snapshot_interval_sec": {{ .Values.config.raft.snapshotIntervalSec }},
        "snapshot_threshold": {{ .Values.config.raft.snapshotThreshold }},
        "trailing_logs": {{ .Values.config.raft.trailingLogs }},
        "max_append_entries": {{ .Values.config.raft.maxAppendEntries }}
      },
      "apply_lag_readiness_threshold": {{ .Values.config.applyLagReadinessThreshold }},
      "apply_lag_threshold": {{ .Values.config.applyLagThreshold }}
    }