{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    {{- include "kave.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    {{- include "kave.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    {{- include "kave.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-prometheus
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-prometheus
  apiGroup: rbac.authorization.k8s.io
{{- end }}
