{{- if .Values.traefik.enabled -}}
{{- $apiGroup := .Values.traefik.apiGroup | default "traefik.io" -}}
apiVersion: {{ $apiGroup }}/v1alpha1
kind: Middleware
metadata:
    name: kave-ratelimiter
spec:
    rateLimit:
        average: 500
        burst: 1000
---
apiVersion: {{ $apiGroup }}/v1alpha1
kind: IngressRoute
metadata:
    name: {{ include "kave.name" . }}
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`{{ .Values.kaveDomain }}`)
      kind: Rule
      middlewares:
        - name: "kave-ratelimiter"
      services:
        - name: {{ .Values.serviceConfig.externalService.name }}
          port: 80
  tls:
    # since cert-manager sets this secret, no certResolver is needed
    secretName: {{ .Values.tls.publicTlsName }}
{{- end}}