apiVersion: v2
name: kave
description: >
  A raft-backed distributed KV store with MVCC, leases,
  watches and secret keys protected by Oblivious Transfer.
type: application
version: 0.2.3 # bumped on each change to the chart
appVersion: "" # patched by CI with git short SHA

keywords:
  - raft
  - key-value-store
  - mvcc
  - lease
  - oblivious-transfer
  - distributed-systems

maintainers:
  - name: Balits Péter Márton
    url: https://github.com/balits

sources:
  - https://github.com/balits/kave