kaveDomain: kave.balits.net

image:
  registry: "ghcr.io"
  repository: "balits/kave"
  tag: "" # must be set via --set image.tag=<sha>
  pullPolicy: Always

voters:
  replicas: 3

ports:
  raft: 7000
  http: 8000

config:
  adminAuthToken: "-" # gets injected through ENV instead of config.json
  logger: 
    kind: "text" # text | json | discard
    level: "debug" # debug | info | warn | error
  checkpointIntervalMinutes: 5
  peerDiscovery:
    mode: "dynamic"
  kv:
    maxKeySize: 512
    maxValueSize: 1024
  storage:
    kind: "boltdb"
    dataDir: "/data"
  compaction:
    threshold: 5
    intervalMinutes: 10
    maxRevGap: 10
  ot:
    slotCount: 32
    slotSize: 64
    tokenTTLSec: 60
  ratelimiter:
    read: 
      rps: 300
      burst: 600
    write: 
      rps: 100
      burst: 200
  mtls:
    certFile: "/tls/raft/tls.crt"
    keyFile: "/tls/raft/tls.key"
    caFile: "/tls/raft/ca.crt"

serviceConfig:
  externalService:
    port: 80
    name: "kave-external"
  headlessService:
    name: "kave-headless"

storage:
  size: 20Gi
  # Empty "" uses the cluster default StorageClass.
  # Known values for specific platforms:
  #   Civo:  "civo-volume"
  #   GKE:   "standard" or "premium-rwo"
  #   Kind:  "standard" (requires Rancher local-path provisioner)
  #   AKS:   "managed-csi"
  storageClassName: ""

healthcheck:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3

pdb: {}  # minAvailable computed dynamically as div(N+1, 2)

traefik:
  enabled: false # local cluster doesnt need it
  apiGroup: "traefik.io"  # "traefik.containo.us" for Traefik < v2.10

tls:
  email: balitspm@gmail.com
  publicTlsName: "kave-public-tls"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

prometheus:
  enabled: false
