kaveDomain: kave.balits.net

image:
  registry: "ghcr.io"
  repository: "balits/kave"
  tag: "latest"
  pullPolicy: Always

voters:
  replicas: 3

ports:
  raft: 7000
  http: 8000

config:
  adminAuthToken: "-" # gets injected through ENV instead of config.json
  logger: 
    kind: "text" # text | json | discard
    level: "debug" # debug | info | warn | error
  checkpointIntervalMinutes: 5
  peerDiscovery:
    mode: "dynamic"
  kv:
    maxKeySize: 512
    maxValueSize: 1024
  storage:
    kind: "boltdb"
    dataDir: "/data"
  compaction:
    threshold: 5
    intervalMinutes: 10
    maxRevGap: 10
  ot:
    slotCount: 32
    slotSize: 64
    tokenTTLSec: 60
  ratelimiter:
    read: 
      rps: 300
      burst: 600
    write: 
      rps: 100
      burst: 200
  mtls:
    certFile: "/tls/raft/tls.crt"
    keyFile: "/tls/raft/tls.key"
    caFile: "/tls/raft/ca.crt"

serviceConfig:
  externalService:
    port: 80
    name: "kave-external"
  headlessService:
    name: "kave-headless"

storage:
  size: 20Gi #out of 40 on a small civo vm
  storageClassName: "" # todo: might need to change on different platform

healthcheck:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3

pdb:
  minAvailable: 2 # for 3 voters

traefik:
  enabled: false # local cluster doesnt need it

tls:
  email: balitspm@gmail.com
  publicTlsName: "kave-public-tls"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

prometheus:
  enabled: false
  serviceMonitor:
    labels:
      release: prometheus
    interval: 10s
    scrapeTimeout: 10s

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false