name: Rolling update

# Rolling should happen on pushes/prs to main, the CI branch and additionaly as a manual dispatch
on:
  push:
    branches: ["main", "feature/ci", "feature/next"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KAVE_DOMAIN: kave.balits.net

jobs:
  test:
    name: Lint & run Unit and Ingegration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/unit-integ-test

  build-img:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: test 
    permissions:
      contents: read
      packages: write
    outputs:
      # steps.<id>
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build-and-push-image
        id: build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          image_name: ${{ env.IMAGE_NAME }}
      
  # skipped on CI cuz portforwarding + PDB is cursed
  # smoke:
  #   name: Smoke test on kind cluster
  #   runs-on: ubuntu-latest
  #   needs: build-img
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/smoke-test
  #       with:
  #         app_name: "kave"
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         image_registry: ${{ env.REGISTRY }}
  #         image_repo: ${{ env.IMAGE_NAME }}
  #         image_tag: latest

  deploy-k8s:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-img
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/next')) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v6
      - name: Deploy K8S to CIVO
        uses: "./.github/actions/deploy-k8s-to-civo"
        with:
          kubeconfig_b64: ${{ secrets.KUBECONFIG_B64 }}
          app_name: "kave" # just to be explicit
          image_tag: ${{ needs.build-img.outputs.image_tag }}
          admin_token: "${{ secrets.ADMIN_TOKEN }}" # quote here to be safe

  extract-helm-config-values:
    name: Extract config values from the helm chart  
    runs-on: ubuntu-latest
    needs: deploy-k8s
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/next')) || github.event_name == 'workflow_dispatch'
    outputs:
      kave_ot_slot_count:  ${{ steps.extract-values.outputs.kave_ot_slot_count }}
      kave_ot_slot_size:   ${{ steps.extract-values.outputs.kave_ot_slot_size }}
    steps:
      - uses: actions/checkout@v6
      - name: Extract values
        id: extract-values
        shell: bash
        run: |
          SLOT_COUNT=$(yq eval '.config.ot.slotCount' ./charts/kave/values.yaml)
          SLOT_SIZE=$(yq eval '.config.ot.slotSize' ./charts/kave/values.yaml)
          echo "kave_ot_slot_count=$SLOT_COUNT" >> $GITHUB_OUTPUT
          echo "kave_ot_slot_size=$SLOT_SIZE" >> $GITHUB_OUTPUT

  deploy-ui:
    name: Deploy UI to Github Pages
    runs-on: ubuntu-latest
    needs: extract-helm-config-values
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/next')) || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-ui.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/deploy-ui-to-gh-pages
        id: deploy-ui
        with:
          cluster_url: "https://${{ env.KAVE_DOMAIN }}"
          kave_ot_slot_size: ${{ needs.extract-helm-config-values.outputs.kave_ot_slot_size }}
          kave_ot_slot_count: ${{ needs.extract-helm-config-values.outputs.kave_ot_slot_count }}
          admin_token: "${{ secrets.ADMIN_TOKEN }}" # quote here to be safe
